In [102]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D,Dense,Flatten,Conv2D,Dense,GlobalMaxPooling1D 
from tensorflow.keras.models import Sequential, Model


## نگاهی عمیق تر به لایه ها


#### دسترسی به وزن های لایه ها


In [57]:
model = tf.keras.applications.MobileNet(weights= 'imagenet',
                                         include_top = True)

17227776/17225924 [==============================] - 3s 0us/step


In [58]:
model.summary()

Model: "mobilenet_1.00_224"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv1_pad (ZeroPadding2D)    (None, 225, 225, 3)       0         
_________________________________________________________________
conv1 (Conv2D)               (None, 112, 112, 32)      864       
_________________________________________________________________
conv1_bn (BatchNormalization (None, 112, 112, 32)      128       
_________________________________________________________________
conv1_relu (ReLU)            (None, 112, 112, 32)      0         
_________________________________________________________________
conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)      288       
_________________________________________________________________
conv_dw_1_bn (BatchNormaliza (None, 112, 112, 32

اطلاعات مربوط به لایه های یک شبکه در مشخصه `layers` آن ذخیره شده است.

In [59]:
len(model.layers)

93

In [60]:
model.layers[2]

 برای این که به وزن های یک لایه دسترسی پیدا کنیم (اگر آن لایه وزنی داشته باشد) با مشخصه `weights` قابل دسترسی هستند.

In [65]:
model.layers[3].weights[0]

<tf.Variable 'conv1_bn_2/gamma:0' shape=(32,) dtype=float32, numpy=
array([ 0.97061753,  0.6502549 ,  0.2254817 ,  0.52415645,  0.98184997,
        0.6788391 ,  1.1129196 ,  0.34201714,  0.6771581 ,  3.3115928 ,
        0.83776003,  1.0192714 ,  0.30443215,  0.4222344 , -0.2554651 ,
        0.96727175,  0.90101403,  0.86320865,  0.86195886,  0.7156465 ,
        1.0060233 ,  0.53907305,  1.3887119 ,  0.24158667,  0.7830971 ,
        0.672174  ,  3.0135353 ,  1.195009  ,  1.8365439 ,  0.47269213,
        0.45962656,  1.0022334 ], dtype=float32)>

In [66]:
base_model.layers[3].get_weights()[0]

array([ 0.97061753,  0.6502549 ,  0.2254817 ,  0.52415645,  0.98184997,
        0.6788391 ,  1.1129196 ,  0.34201714,  0.6771581 ,  3.3115928 ,
        0.83776003,  1.0192714 ,  0.30443215,  0.4222344 , -0.2554651 ,
        0.96727175,  0.90101403,  0.86320865,  0.86195886,  0.7156465 ,
        1.0060233 ,  0.53907305,  1.3887119 ,  0.24158667,  0.7830971 ,
        0.672174  ,  3.0135353 ,  1.195009  ,  1.8365439 ,  0.47269213,
        0.45962656,  1.0022334 ], dtype=float32)

bias های یک لایه هم با مشخصه `bias` قابل دستترسی هستند.

In [80]:
model.layers[90].bias[0:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.48195136,  0.02448254, -0.98349696, -1.0550407 ,  0.1832502 ,
       -0.12676108,  0.20039281, -0.91389215, -1.1940612 , -1.5195633 ],
      dtype=float32)>

In [82]:
model.layers[90].kernel[0]

<tf.Tensor: shape=(1, 1024, 1000), dtype=float32, numpy=
array([[[-0.00136319, -0.05997207, -0.00945091, ..., -0.12088422,
          0.04772888,  0.10453417],
        [-0.09380977,  0.0133763 , -0.00086663, ..., -0.05051607,
         -0.05330694, -0.00499932],
        [ 0.03785546,  0.02643952,  0.03207906, ...,  0.06625971,
         -0.10837644, -0.02584988],
        ...,
        [-0.01420777, -0.08234182, -0.05374264, ...,  0.11939939,
         -0.04741941, -0.02354525],
        [-0.02142392, -0.0442558 ,  0.03908358, ..., -0.0139262 ,
          0.14381737, -0.11744042],
        [-0.06758978,  0.06164968,  0.1083982 , ...,  0.06461229,
         -0.01201531,  0.05659112]]], dtype=float32)>

برای دسترسی به یک لایه یک راه دیگر استفاده از نام آن لایه به جای ایندکس است که به خصوص وقتی شبکه ما بزرگ است به کار می آید.
 مثلا فرض کنید می خواهیم به آخرین لایه کانولوشنال شبکه دسترسی پیدا کنیم.

In [47]:
base_model.get_layer('conv5_block3_3_conv')

وزن ها به صورت مشابه قابل دسترسی هستند.


In [48]:
base_model.get_layer('conv5_block3_3_conv').weights

[<tf.Variable 'conv5_block3_3_conv_3/kernel:0' shape=(1, 1, 512, 2048) dtype=float32, numpy=
 array([[[[-0.00772033,  0.0285685 , -0.0311284 , ..., -0.00376943,
            0.00396393, -0.01859178],
          [ 0.03072583, -0.02049609,  0.00851315, ..., -0.03072169,
            0.09537231, -0.01491823],
          [ 0.00430369,  0.00874794, -0.00027265, ..., -0.00887997,
            0.00560437, -0.02863607],
          ...,
          [ 0.01828984, -0.01196646, -0.00106144, ..., -0.00687517,
            0.00607187, -0.04117712],
          [-0.00993001, -0.00776328, -0.02632025, ..., -0.02515809,
            0.01466563,  0.00475405],
          [ 0.00103569,  0.01750279,  0.00685418, ...,  0.02908638,
           -0.00971192,  0.02699419]]]], dtype=float32)>,
 <tf.Variable 'conv5_block3_3_conv_3/bias:0' shape=(2048,) dtype=float32, numpy=
 array([-1.5847744e-08, -5.5954280e-07,  9.1473552e-08, ...,
        -3.5979106e-08, -9.8053647e-07, -1.8873895e-07], dtype=float32)>]

In [35]:
base_model.get_layer('conv5_block1_2_pad').weights 

[]

In [52]:
#func_model = Model( inputs = base_model, 
#outputs = Dense(10,activation = 'softmax'))
#func_model.summary()

#### دسترسی پیدا کردن به ورودی و خروجی لایه ها

In [39]:
base_model.get_layer('conv5_block1_2_pad').input

<tf.Tensor 'conv5_block1_1_relu_3/Identity:0' shape=(None, 7, 7, 512) dtype=float32>

In [40]:
base_model.get_layer('conv5_block1_2_pad').output

<tf.Tensor 'conv5_block1_2_pad_3/Identity:0' shape=(None, 9, 9, 512) dtype=float32>

In [41]:
base_model.input

<tf.Tensor 'input_4:0' shape=(None, 224, 224, 3) dtype=float32>

In [44]:
seq_model = Sequential([base_model.input, 
Dense(10,activation = 'softmax')])
seq_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 224, 224, 10)      40        
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


### فریز کردن وزن های لایه ها

پیش از این در خصوص فریز کردن وزن های مدل برای انتقال یادگیری به صورت مفصل بحث کردیم. در این جا می خواهیم ببینیم که چطور می توانیم وزن های یک لایه خاص  از مدل را فریز کنیم.

In [115]:
model = tf.keras.applications.MobileNet(weights= 'imagenet',
                                        input_shape=(150,150,3),
                                         include_top = False)
#model.summary()
model.input

<tf.Tensor 'input_15:0' shape=(None, 150, 150, 3) dtype=float32>


وقتی که یک لایه را به مدل اضافه می کنیم می توانیم با قرار دادن `trainable = False` کاری کنیم که وزن های آن لایه فریز شوند و در زمان آموزش به روز رسانی نشوند.



In [111]:
model.input

<tf.Tensor 'input_12:0' shape=(None, None, None, 3) dtype=float32>

In [ ]:
model_1 = Sequential([
    model,
    Flatten(),
    Dense(100,activation = 'relu', trainable = False),
    Dense(10,activation = 'softmax')
])

با استفاده از API فاکشنال به صورت زیر خواهد بود

In [120]:


inputs = model.input #keras.layers.Input(shape = (150,150,3))
x = model(inputs,training = False)
x = Flatten()(x)
x = Dense(128,activation='relu',trainable = False)(x)
outputs = Dense(5,activation='softmax' )(x)
final_model = Model(inputs,outputs)

In [99]:
model_1.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
mobilenet_1.00_224 (Model)   (None, None, None, 1024)  3228864   
_________________________________________________________________
flatten_5 (Flatten)          (None, None)              0         
Total params: 3,228,864
Trainable params: 2,158,400
Non-trainable params: 1,070,464
_________________________________________________________________


یک راه دیگر هم استفاده از متد `get_layer()` استفاده است.

In [96]:
model.get_layer('conv_pw_13').trainable = False
model.get_layer('conv_pw_13_relu').trainable = False

باید مدل را کامپایل کنیم تا  این تغییرات اعمال شوند.

In [87]:
model.compile(loss = 'categorical_crossentropy')

دقت کنید که این که می توانیم لایه های مختلف شبکه را فریز کنیم به این معنا نیست که این کار کار خوبی است و صرفا به عنوان مثال این کار را انجام دهیم.

### لایه های lambda

### ساخت لایه های اختصاصی


برای ساخت یک لایه کراس سه تابع را باید در زمان ایجاد کلاس این لایه پیاده سازی کنیم:

1. یک تابع که وزن های قابل آموزش مدل را تعریف می کند. (تابع build)

2. یک تابع که منطق لایه را مشخص می کند (تابع call)

3. و در نهایت یک تابع که ابعاد خروجی را محاسبه و تعیین می کند.

لایه های تعریف شده باید از کلاس tf.keras.layers.Layers به ارث برده شده باشند.

### پیاده سازی لایه  Noisy Relu

In [12]:
class NoisyRelu(tf.keras.layers.Layer):
    def __init__(self,**kwargs):
        super(NoisyRelu,self).__init__(**kwargs)

    

اگر به تعریف تابع فعال سازی noisy relu دقت کرده باشید می بینید که این لایه هیچ پارامتر آموزش پذیری ندارد. برای همین نیازی به تابع build نداریم.



In [13]:
def call(self,x):
    tf.maximum(0, x + tf.random.normal())

In [14]:
def compute_output_shape(self,input_shape):
    return input_shape

In [25]:
tf.random.normal(shape = (1,1))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.16257451]], dtype=float32)>

حالا می توانیم همه این ها را کنار هم قرار دهیم.

In [30]:
class NoisyRelu(tf.keras.layers.Layer):
    def __init__(self,**kwargs):
        super(NoisyRelu,self).__init__(**kwargs)
    def call(self,x):
        return tf.maximum(0.0, x + tf.random.normal(shape = (1,1)))
    def compute_output_shape(self,input_shape):
        return input_shape

#### آموزش و امتحان لایه جدید ساخته شده

In [34]:
model = Sequential()
model.add(Conv2D(filters = 15,kernel_size=3, input_shape = (28,28,1)))
model.add(NoisyRelu())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [35]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 26, 26, 15)        150       
_________________________________________________________________
noisy_relu_6 (NoisyRelu)     (None, 26, 26, 15)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 15)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 2535)              0         
_________________________________________________________________
dense (Dense)                (None, 100)               253600    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1010      
Total params: 254,760
Trainable params: 254,760
Non-trainable params: 0
________________________________________________

### پیاده سازی لایه Attention

حالا نوبت این است که تابع build را تعریف کنیم.



In [ ]:
def build(self,input_shape):
    self.

In [ ]:
class ScaledDotProductAttention(Layer):
    """
        Implementation according to:
            "Attention is all you need" by A Vaswani, N Shazeer, N Parmar (2017)
    """

    def __init__(self, return_attention=False, **kwargs):    
        self._return_attention = return_attention
        self.supports_masking = True
        super(ScaledDotProductAttention, self).__init__(**kwargs)
    
    def compute_output_shape(self, input_shape):
        self._validate_input_shape(input_shape)

        if not self._return_attention:
            return input_shape[-1]
        else:
            return [input_shape[-1], [input_shape[0][0], input_shape[0][1], input_shape[1][2]]]
    
    def _validate_input_shape(self, input_shape):
        if len(input_shape) != 3:
            raise ValueError("Layer received an input shape {0} but expected three inputs (Q, V, K).".format(input_shape))
        else:
            if input_shape[0][0] != input_shape[1][0] or input_shape[1][0] != input_shape[2][0]:
                raise ValueError("All three inputs (Q, V, K) have to have the same batch size; received batch sizes: {0}, {1}, {2}".format(input_shape[0][0], input_shape[1][0], input_shape[2][0]))
            if input_shape[0][1] != input_shape[1][1] or input_shape[1][1] != input_shape[2][1]:
                raise ValueError("All three inputs (Q, V, K) have to have the same length; received lengths: {0}, {1}, {2}".format(input_shape[0][0], input_shape[1][0], input_shape[2][0]))
            if input_shape[0][2] != input_shape[1][2]:
                raise ValueError("Input shapes of Q {0} and V {1} do not match.".format(input_shape[0], input_shape[1]))
    
    def build(self, input_shape):
        self._validate_input_shape(input_shape)
        
        super(ScaledDotProductAttention, self).build(input_shape)
    
    def call(self, x, mask=None):
        q, k, v = x
        d_k = q.shape.as_list()[2]

        # in pure tensorflow:
        # weights = tf.matmul(x_batch, tf.transpose(y_batch, perm=[0, 2, 1]))
        # normalized_weights = tf.nn.softmax(weights/scaling)
        # output = tf.matmul(normalized_weights, x_batch)
        
        weights = K.batch_dot(q,  k, axes=[2, 2])

        if mask is not None:
            # add mask weights
            if isinstance(mask, (list, tuple)):
                if len(mask) > 0:
                    raise ValueError("mask can only be a Tensor or a list of length 1 containing a tensor.")

                mask = mask[0]

            weights += -1e10*(1-mask)

        normalized_weights = K.softmax(weights / np.sqrt(d_k))
        output = K.batch_dot(normalized_weights, v)
        
        if self._return_attention:
            return [output, normalized_weights]
        else:
            return output

### منابع

https://github.com/zimmerrol/keras-utility-layer-collection/blob/master/kulc/layer_normalization.py
https://github.com/zimmerrol/keras-utility-layer-collection
    https://github.com/Zelgunn/CustomKerasLayers